import fs from "node:fs";
import path from "node:path";

export const writeBiUiHelperGuidance = (runDir: string): string => {
  const filePath = path.join(runDir, "input", "bi-ui-helper-guidance.md");
  const content = [
    "# BI UI Helper Guidance v1.0",
    "",
    "本檔是 BI domain 的安全 UI 操作備忘,目標是減少 Codex 反覆摸索頁面。它不是測試規則的替代品,也不是批次執行授權。",
    "",
    "## 不可越界",
    "",
    "- 不可用內部函式設定狀態,例如 `window.addFilter()`、`window.addFieldToSelection()`、`window.selectDateRangePreset()`。",
    "- 不可用 `browser_evaluate` 觸發 click/change/input 等會改狀態的事件。",
    "- 不可直接打 BI API 取得測試結果。",
    "- 不可在一段 helper 中跑多個 case。helper 只能服務當前 case 的單一操作片段。",
    "- 每個 case 完成後必須先寫入結果與 evidence,再讀下一個 case。",
    "",
    "## 安全讀取",
    "",
    "- 可用 Playwright snapshot/DOM read 確認 UI 狀態。",
    "- 可用 read-only `page.evaluate` 讀 DOM、Chart.js data、network performance entries。",
    "- 讀取不等於 evidence 通過；PASS/FAIL 仍需當前 run 的 UI 操作或觀察鏈。",
    "- Evidence 優先順序: DOM/form state > network observation > chart/table data > screenshot。",
    "- Screenshot 用於 Tool Bridge、FAIL/bug、重大狀態轉換、final evidence；bug 若無 screenshot 必須寫明原因。",
    "- 若 DOM/network evidence 已足以支撐 PASS/FAIL，但 screenshot timeout，不可反覆重試 full-page screenshot；最多改試一次較小 viewport/element screenshot。仍失敗就記 `screenshot_unavailable_reason` 並繼續寫結構化 evidence。",
    "",
    "## 常見操作節奏",
    "",
    "### 開啟專案",
    "",
    "1. 先 snapshot 左側 sidebar。",
    "2. 依 testcase 目標模式展開 `我的自訂 > 拼貼模式 / 明細檢視 / 指標趨勢`。",
    "3. 點擊目標專案後重新 snapshot,確認右側出現專案標題或報表列表。",
    "",
    "### 新增欄位",
    "",
    "1. 點 visible `+ 新增欄位` / `+ 選擇主欄位`。",
    "2. 在 visible dropdown/list 裡選 testcase 指定欄位。",
    "3. 重新讀 DOM,確認欄位列文字或 select value 已變成目標欄位。",
    "",
    "### 設定時間",
    "",
    "1. 點時間按鈕,用 UI 選擇 testcase 指定區間或日期。",
    "2. 點確認後重新讀按鈕文字。",
    "3. 如果按鈕文字與狀態清理 checklist 逐字不符,不可假設等價,必須修正或 BLOCKED。",
    "",
    "### 執行與驗證",
    "",
    "1. 按 `執行 / 查詢 / 搜尋` 後,讀 network performance 或頁面結果確認有新的 preview/request/圖表變化。",
    "2. 沒有新的 request 或 DOM/chart 證據時,不要宣稱已執行成功。",
    "3. 結果判定需符合 testcase 的測試標的與 evidence policy。",
    "4. 截圖是人類佐證,不是唯一 evidence；能用結構化資料比對時優先用結構化資料。",
    "5. Metadata/dropdown observation case 以 DOM extraction 的欄位清單與 count 為主 evidence；screenshot 只作輔助,不可因截圖 timeout 阻塞已取得的結構化結論。",
    "",
    "### 儲存/刪除/原生 Dialog",
    "",
    "1. 儲存、刪除、接受 native alert/confirm 前,先輸出 Tool Bridge request。",
    "2. 未收到本 run 的 Tool Bridge response 前不可處理 dialog。",
    "3. 儲存新報表要用 timestamped 臨時名稱,不可覆蓋既有主測試資源。",
    "",
    "## One Case Guard",
    "",
    "此 guidance 不允許加速成批次執行。若當前 case 需要下一個 case 的互補資料,只能讀下一個 case 的 JSON 做判斷依據；正式 UI 操作仍必須逐 case 執行、逐 case 寫入結果。",
    ""
  ].join("\n");
  fs.writeFileSync(filePath, content);
  return filePath;
};
